var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.arrayFromIterator=function(a){for(var b,f=[];!(b=a.next()).done;)f.push(b.value);return f};$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,f){if(a==Array.prototype||a==Object.prototype)return a;a[b]=f.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var f=a[b];if(f&&f.Math==Math)return f}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var f=$jscomp.propertyToPolyfillSymbol[b];if(null==f)return a[b];f=a[f];return void 0!==f?f:a[b]};
$jscomp.polyfill=function(a,b,f,e){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,f,e):$jscomp.polyfillUnisolated(a,b,f,e))};$jscomp.polyfillUnisolated=function(a,b,f,e){f=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var d=a[e];if(!(d in f))return;f=f[d]}a=a[a.length-1];e=f[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(f,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,f,e){var d=a.split(".");a=1===d.length;e=d[0];e=!a&&e in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var n=0;n<d.length-1;n++){var c=d[n];if(!(c in e))return;e=e[c]}d=d[d.length-1];f=$jscomp.IS_SYMBOL_NATIVE&&"es6"===f?e[d]:null;b=b(f);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,d,{configurable:!0,writable:!0,value:b}):b!==f&&($jscomp.propertyToPolyfillSymbol[d]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(d):$jscomp.POLYFILL_PREFIX+d,d=
$jscomp.propertyToPolyfillSymbol[d],$jscomp.defineProperty(e,d,{configurable:!0,writable:!0,value:b})))};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(f){}return!1};$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};
$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};
$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};
$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};
$jscomp.generator.Context.prototype.yieldAll=function(a,b){a=$jscomp.makeIterator(a);var f=a.next();$jscomp.generator.ensureIteratorResultIsObject_(f);if(f.done)this.yieldResult=f.value,this.nextAddress=b;else return this.yieldAllIterator_=a,this.yield(f.value,b)};$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};
$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,f){f?this.finallyContexts_[f]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){b=this.finallyContexts_.splice(b||0)[0];if(b=this.abruptCompletion_=this.abruptCompletion_||b){if(b.isException)return this.jumpToErrorHandler_();void 0!=b.jumpTo&&this.finallyAddress_<b.jumpTo?(this.nextAddress=b.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(f){return{value:f,done:!0}},a,this.context_.return);this.context_.return(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,f){try{var e=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(e);if(!e.done)return this.context_.stop_(),e;var d=e.value}catch(n){return this.context_.yieldAllIterator_=null,this.context_.throw_(n),this.nextStep_()}this.context_.yieldAllIterator_=null;f.call(this.context_,d);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this.throw=function(b){return a.throw_(b)};this.return=function(b){return a.return_(b)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){b=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&a.prototype&&$jscomp.setPrototypeOf(b,a.prototype);return b};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(e){return a.next(e)}function f(e){return a.throw(e)}return new Promise(function(e,d){function n(c){c.done?e(c.value):Promise.resolve(c.value).then(b,f).then(n,d)}n(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.initSymbol=function(){};$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(d,n){this.$jscomp$symbol$id_=d;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:n})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var f=0,e=function(d){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b("jscomp_symbol_"+(d||"")+"_"+f++,d)};return e},"es6","es3");$jscomp.initSymbolIterator=function(){};
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),f=0;f<b.length;f++){var e=$jscomp.global[b[f]];"function"===typeof e&&"function"!=typeof e.prototype[a]&&$jscomp.defineProperty(e.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.initSymbolAsyncIterator=function(){};$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function f(c){return c instanceof d?c:new d(function(g,l){g(c)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(c){if(null==this.batch_){this.batch_=[];var g=this;this.asyncExecuteFunction(function(){g.executeBatch_()})}this.batch_.push(c)};var e=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(c){e(c,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var c=
this.batch_;this.batch_=[];for(var g=0;g<c.length;++g){var l=c[g];c[g]=null;try{l()}catch(m){this.asyncThrow_(m)}}}this.batch_=null};b.prototype.asyncThrow_=function(c){this.asyncExecuteFunction(function(){throw c;})};var d=function(c){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var g=this.createResolveAndReject_();try{c(g.resolve,g.reject)}catch(l){g.reject(l)}};d.prototype.createResolveAndReject_=function(){function c(m){return function(r){l||(l=!0,m.call(g,r))}}var g=this,l=!1;
return{resolve:c(this.resolveTo_),reject:c(this.reject_)}};d.prototype.resolveTo_=function(c){if(c===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(c instanceof d)this.settleSameAsPromise_(c);else{a:switch(typeof c){case "object":var g=null!=c;break a;case "function":g=!0;break a;default:g=!1}g?this.resolveToNonPromiseObj_(c):this.fulfill_(c)}};d.prototype.resolveToNonPromiseObj_=function(c){var g=void 0;try{g=c.then}catch(l){this.reject_(l);return}"function"==typeof g?
this.settleSameAsThenable_(g,c):this.fulfill_(c)};d.prototype.reject_=function(c){this.settle_(2,c)};d.prototype.fulfill_=function(c){this.settle_(1,c)};d.prototype.settle_=function(c,g){if(0!=this.state_)throw Error("Cannot settle("+c+", "+g+"): Promise already settled in state"+this.state_);this.state_=c;this.result_=g;this.executeOnSettledCallbacks_()};d.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var c=0;c<this.onSettledCallbacks_.length;++c)n.asyncExecute(this.onSettledCallbacks_[c]);
this.onSettledCallbacks_=null}};var n=new b;d.prototype.settleSameAsPromise_=function(c){var g=this.createResolveAndReject_();c.callWhenSettled_(g.resolve,g.reject)};d.prototype.settleSameAsThenable_=function(c,g){var l=this.createResolveAndReject_();try{c.call(g,l.resolve,l.reject)}catch(m){l.reject(m)}};d.prototype.then=function(c,g){function l(u,v){return"function"==typeof u?function(h){try{m(u(h))}catch(k){r(k)}}:v}var m,r,x=new d(function(u,v){m=u;r=v});this.callWhenSettled_(l(c,m),l(g,r));return x};
d.prototype.catch=function(c){return this.then(void 0,c)};d.prototype.callWhenSettled_=function(c,g){function l(){switch(m.state_){case 1:c(m.result_);break;case 2:g(m.result_);break;default:throw Error("Unexpected state: "+m.state_);}}var m=this;null==this.onSettledCallbacks_?n.asyncExecute(l):this.onSettledCallbacks_.push(l)};d.resolve=f;d.reject=function(c){return new d(function(g,l){l(c)})};d.race=function(c){return new d(function(g,l){for(var m=$jscomp.makeIterator(c),r=m.next();!r.done;r=m.next())f(r.value).callWhenSettled_(g,
l)})};d.all=function(c){var g=$jscomp.makeIterator(c),l=g.next();return l.done?f([]):new d(function(m,r){function x(h){return function(k){u[h]=k;v--;0==v&&m(u)}}var u=[],v=0;do u.push(void 0),v++,f(l.value).callWhenSettled_(x(u.length-1),r),l=g.next();while(!l.done)})};return d},"es6","es3");$jscomp.findInternal=function(a,b,f){a instanceof String&&(a=String(a));for(var e=a.length,d=0;d<e;d++){var n=a[d];if(b.call(f,n,d,a))return{i:d,v:n}}return{i:-1,v:void 0}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(b,f){return $jscomp.findInternal(this,b,f).v}},"es6","es3");
function initP2P(a,b,f,e,d){var n={iceServers:["",1,2,3,4].map(function(h){return{urls:"stun:stun"+h+".l.google.com:19302"}})},c=null,g={id:"",master:!0,targets:[]},l=function(h){switch(h.type){case 1:g=Object.assign({},g,{id:h.payload});a(g.id);break;case 4:g=Object.assign({},g,{targets:[].concat($jscomp.arrayFromIterable(g.targets),[{id:h.payload,candidates:[],pc:null,channel:null}])});break;case 3:g=Object.assign({},g,{targets:g.targets.filter(function(k){return k.id!==k.payload})});break;case 2:g=
{id:"",master:!0,targets:[]};break;case 5:g=Object.assign({},g,{master:h.payload});break;case 6:g=Object.assign({},g,{targets:g.targets.map(function(k){return k.id===h.payload.id?Object.assign({},k,{candidates:[].concat($jscomp.arrayFromIterable(k.candidates),[h.payload.candidate])}):k})});break;default:e(h)}},m=function(h){return g.targets.find(function(k){return k.id===h})},r=function(h,k){h.channel=k;k.onopen=function(){return b(h.id)};k.onclose=function(){l({type:3,payload:h.id});f(h.id);k.onopen=
k.onclose=k.onmessage=null};k.onmessage=function(p){return e(h.id,p)}},x=function(h){if(!h.pc){var k=h.pc=new RTCPeerConnection(n);k.onicecandidate=function(p){(p=p.candidate)&&c.send({to:h.id,data:{type:6,payload:{id:g.id,candidate:p}}})};k.onnegotiationneeded=function(){var p,w,y;return $jscomp.asyncExecutePromiseGeneratorProgram(function(q){switch(q.nextAddress){case 1:if(!g.master)return q.return();q.setCatchFinallyBlocks(2);p=k;w=p.setLocalDescription;return q.yield(k.createOffer(),5);case 5:return q.yield(w.call(p,
q.yieldResult),4);case 4:c.send({to:h.id,data:{id:g.id,desc:k.localDescription}});q.leaveTryBlock(0);break;case 2:y=q.enterCatchBlock(),d(y),q.jumpToEnd()}})};k.oniceconnectionstatechange=function(){"disconnected"==k.iceConnectionState&&(l({type:3,payload:h.id}),f(h.id))};g.master?r(h,k.createDataChannel("data")):k.ondatachannel=function(p){p=p.channel;return r(m(h.id),p)}}},u=function(h){var k=m(h);h=k.pc;for(k=k.candidates;k.length;)try{h.addIceCandidate(new RTCIceCandidate(k.shift()))}catch(p){d(p)}};
c=io({upgrade:!1,transports:["websocket"]});c.on("connect",function(){return console.log("Connected.")});c.on("disconnect",function(){l({type:2});d({err:"disconnected"})});c.on("error",console.error);c.on("message",function(h){var k,p,w,y,q,z,A;return $jscomp.asyncExecutePromiseGeneratorProgram(function(t){switch(t.nextAddress){case 1:if(h.type)return l(h),t.return(4===h.type&&x(m(h.payload)));if(!h.desc){t.jumpTo(0);break}k=h;p=k.desc;w=k.id;y=m(w);q=y.pc;switch(p.type){case "offer":return t.jumpTo(3);
case "answer":return t.jumpTo(4);default:d({err:"Unsupported SDP type."})}t.jumpTo(0);break;case 3:return t.yield(q.setRemoteDescription(p),6);case 6:return z=q,A=z.setLocalDescription,t.yield(q.createAnswer(),8);case 8:return t.yield(A.call(z,t.yieldResult),7);case 7:c.send({to:w,data:{id:g.id,desc:q.localDescription}});u(w);t.jumpTo(0);break;case 4:return t.yield(q.setRemoteDescription(p),9);case 9:u(w),t.jumpTo(0)}})});var v=function(h){return function(k){(k=k.channel)?"open"===k.readyState&&k.send(h):
d({err:"Channel not initialized."})}};return{isMaster:function(){return g.master},getId:function(){return g.id},connect:function(h){l({type:5,payload:!1});l({type:4,payload:h});c.send({to:h,data:{type:4,payload:g.id}});x(m(h))},send:function(h,k){v(k)(m(h))},sendAll:function(h){g.targets.forEach(v(h))}}}
var ppService={pp:null,masterId:"",isMaster:function(){return this.pp&&this.pp.isMaster()},init:function(a,b){var f=this;this.pp?location.hash=playerService.me.id:this.pp=initP2P(function(e){var d=playerService.me,n=getHash();playerService.remove(d.id);d.setId(e);playerService.add(d);f.pp.isMaster()&&!n?(location.hash=e,f.masterId=e):n&&(f.masterId=n,f.pp.connect(f.masterId))},function(e){return playerService.add(new Player(e,a.drone(0,0,DRONE_RADIUS),keepGoingAi))},function(e){return playerService.remove(e)},
function(e,d){e=JSON.parse(d.data);switch(e[0]){case 9:return playerService.players[e[1][0]].name=e[1][1];case 10:return levelService.startTime=e[1],levelService.index=e[2],e=viewManager.views[RACE_VIEW],e.leaderboard.isDone=e.isDone=!0;case 7:return playerService.addCommand(e[1]);case 8:for(playerService.sync(e[1]),e=playerService.me,d=0;e.commands.hasNonApplied()&&!(e.commands.apply(e.drone,e.specs),a.physics.step(b),5<++d););}},console.error)}};
